[package]
name = "skiffa-core"
version = "0.1.0"
edition = "2021"
description = "Core of skiffa"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.Skiffa.org"
keywords = ["openapi", "api"]
repository = "git@github.com:LuvDaSun/Skiffa"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
serde = { version = "^1.0.158", features = ["derive"] }
serde_json = "^1.0.94"
quote = "^1.0.35"
futures = { version = "0.3.30" }
serde_yaml = "^0.9.31"
once_cell = "^1.19.0"
regex = "^1.10.3"
urlencoding = "2.1.3"
semver = "1.0.23"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
gloo = "0.11.0"

[target.'cfg(not(target_os = "unknown"))'.dependencies]
surf = "2.3.2"
tokio = { version = "1.38.0", features = ["full"] }

[lib]
crate-type = ["rlib", "cdylib"]
