on:
  push:
    branches:
      - "*"
    paths:
      - "*"
      - .github/**
      - packages/**

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run formatting

  spelling:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run spelling

  audit:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm --workspaces audit --audit-level high
